/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.aespi.jdbc.view;

import br.edu.aespi.jdbc.controller.NovoController;
import br.edu.aespi.jdbc.model.HeroisDao;
import br.edu.aespi.jdbc.model.Herois;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author hitaloyo
 */
public class TelaNovo extends javax.swing.JFrame {

    /**
     * Creates new form TelaInsertComTabale
     */
    public TelaNovo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLnome = new javax.swing.JLabel();
        jLidSecreto = new javax.swing.JLabel();
        jLhabilidade = new javax.swing.JLabel();
        jBnGravar = new javax.swing.JButton();
        jTfnome = new javax.swing.JTextField();
        jTfIdSecreto = new javax.swing.JTextField();
        jTfHabilidade = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Novo Heroi");
        setBackground(new java.awt.Color(255, 0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        jLnome.setText("Nome");

        jLidSecreto.setText("Identidade Secreta");

        jLhabilidade.setText("Habilidade");

        jBnGravar.setText("Gravar");
        jBnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnGravarActionPerformed(evt);
            }
        });

        jTfnome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTfnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfnomeActionPerformed(evt);
            }
        });

        jTfIdSecreto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTfIdSecreto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfIdSecretoActionPerformed(evt);
            }
        });

        jTfHabilidade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTfHabilidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfHabilidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLnome)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLidSecreto, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLhabilidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jBnGravar))
                            .addComponent(jTfHabilidade)
                            .addComponent(jTfIdSecreto)
                            .addComponent(jTfnome, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(43, 43, 43))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLnome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTfnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLidSecreto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jTfIdSecreto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLhabilidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTfHabilidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jBnGravar)
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTfnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfnomeActionPerformed

    private void jTfIdSecretoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfIdSecretoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfIdSecretoActionPerformed

    private void jTfHabilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfHabilidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfHabilidadeActionPerformed

    private void jBnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnGravarActionPerformed
                String nome = jTfnome.getText();
                String idSecreto = jTfIdSecreto.getText();
                String skill = jTfHabilidade.getText();
                
                jTfnome.setText("");
                jTfIdSecreto.setText("");
                jTfHabilidade.setText("");
                
                NovoController.gravar(nome, idSecreto, skill);
                
                JOptionPane.showMessageDialog(jPanel1, "Gravado", "Novo Heroi", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jBnGravarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBnGravar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLhabilidade;
    private javax.swing.JLabel jLidSecreto;
    private javax.swing.JLabel jLnome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTfHabilidade;
    private javax.swing.JTextField jTfIdSecreto;
    private javax.swing.JTextField jTfnome;
    // End of variables declaration//GEN-END:variables
}
