/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.aespi.jdbc.view;

import br.edu.aespi.jdbc.controller.TableController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author hitaloyo
 */
public class TelaTabela extends javax.swing.JFrame {

    /**
     * Creates new form Table
     */
    public TelaTabela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPTabela = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTherois = new javax.swing.JTable();
        jPAzul = new javax.swing.JPanel();
        jBnEditar = new javax.swing.JButton();
        jBnDeletar = new javax.swing.JButton();
        jPVermelho = new javax.swing.JPanel();
        jBtnPesquisar = new javax.swing.JButton();
        jBnNovoJogo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BDHerois");
        setResizable(false);

        jPTabela.setBackground(new java.awt.Color(102, 102, 102));

        jTherois.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Identidade Secreta", "Habilidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTherois.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTherois);
        if (jTherois.getColumnModel().getColumnCount() > 0) {
            jTherois.getColumnModel().getColumn(0).setResizable(false);
            jTherois.getColumnModel().getColumn(0).setPreferredWidth(5);
            jTherois.getColumnModel().getColumn(1).setResizable(false);
            jTherois.getColumnModel().getColumn(2).setResizable(false);
            jTherois.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPTabelaLayout = new javax.swing.GroupLayout(jPTabela);
        jPTabela.setLayout(jPTabelaLayout);
        jPTabelaLayout.setHorizontalGroup(
            jPTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTabelaLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );
        jPTabelaLayout.setVerticalGroup(
            jPTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTabelaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPAzul.setBackground(new java.awt.Color(0, 204, 204));

        jBnEditar.setText("Editar");
        jBnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnEditarActionPerformed(evt);
            }
        });

        jBnDeletar.setText("Deletar");
        jBnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnDeletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPAzulLayout = new javax.swing.GroupLayout(jPAzul);
        jPAzul.setLayout(jPAzulLayout);
        jPAzulLayout.setHorizontalGroup(
            jPAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAzulLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBnDeletar, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPAzulLayout.setVerticalGroup(
            jPAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPAzulLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBnEditar)
                .addGap(18, 18, 18)
                .addComponent(jBnDeletar)
                .addGap(38, 38, 38))
        );

        jPVermelho.setBackground(new java.awt.Color(255, 0, 0));

        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jBnNovoJogo.setText("Novo Jogo");
        jBnNovoJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnNovoJogoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPVermelhoLayout = new javax.swing.GroupLayout(jPVermelho);
        jPVermelho.setLayout(jPVermelhoLayout);
        jPVermelhoLayout.setHorizontalGroup(
            jPVermelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPVermelhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPVermelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBnNovoJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnPesquisar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPVermelhoLayout.setVerticalGroup(
            jPVermelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPVermelhoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jBtnPesquisar)
                .addGap(18, 18, 18)
                .addComponent(jBnNovoJogo)
                .addContainerGap(294, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPVermelho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPAzul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPTabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPVermelho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBnNovoJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnNovoJogoActionPerformed
        TableController.novo();
    }//GEN-LAST:event_jBnNovoJogoActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed

        try {
            TableController.pesquisar(jTherois);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaTabela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaTabela.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jBnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnEditarActionPerformed
        TableController.editar(jTherois);
    }//GEN-LAST:event_jBnEditarActionPerformed

    private void jBnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnDeletarActionPerformed
        TableController.deletar(jTherois);
    }//GEN-LAST:event_jBnDeletarActionPerformed
        public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTabela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBnDeletar;
    private javax.swing.JButton jBnEditar;
    private javax.swing.JButton jBnNovoJogo;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JPanel jPAzul;
    private javax.swing.JPanel jPTabela;
    private javax.swing.JPanel jPVermelho;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTherois;
    // End of variables declaration//GEN-END:variables
}
